exclude: |
    (?x)^(
        \.git/.*|
        \.cache/.*|
        node_modules/.*|
        ferum_custom/public/dist/.*|
        build/.*|
        dist/.*|
        \.fastmcp-venv/.*
    )$
default_stages: [pre-commit]
fail_fast: false

default_language_version:
  python: python3.12


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "^backend/.*\\.py$"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]
        files: "^backend/.*\\.py$"

      - id: ruff
        name: "Run ruff linter"
        args: ["--extend-ignore=I"]
        files: "^backend/.*\\.py$"

      - id: ruff-format
        name: "Run ruff formatter"
        files: "^backend/.*\\.py$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                ferum_custom/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                ferum_custom/templates/includes/.*|
                ferum_custom/public/js/lib/.*
            )$


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                ferum_custom/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                ferum_custom/templates/includes/.*|
                ferum_custom/public/js/lib/.*
            )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^backend/
        pass_filenames: false
        additional_dependencies:
          - types-redis
        stages: [manual]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. pytest -q
        language: system
        types: [python]
        pass_filenames: false
        stages: [manual]

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
